name: satmvs_res
dependencies:
  - python=3.10
  - gdal
  - numpy<2.0
  - scipy
  - matplotlib
  - tensorboard
  - opencv
  - pyyaml
  - tqdm
  - pip
  - pip:
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
    - tensorboardX
    - plyfile